### ISSUE TITLE
Connecting to Different Service Control Instance Does Nothing

### ISSUE THREAD

**Issue by fafachd** [Particular/ServiceInsight#574] opened 2016-03-30 15:49 UTC
v1.5.6

Connecting to a different ServiceControl instance DOES NOTHING (until ServiceInsight is restarted or refreshed). This results in a bad user experience when switching between Dev, Test, and Prod, environments:
1. User connects to a different SC instance and clicks OK.
2. User waits a long time for the change to take effect.
3. User eventually gives up waiting and restarts SI or clicks Refresh.

Please fix this. You could alternatively update the "Connect to ServiceControl" dialog to say something like: "You must click Refresh for this change to take effect", but that sure feels like a hack. 

Thank you,
Danny

**Comment by robbihun** [comment] 2016-03-30 17:03
Additional Info - it appears that the connection does refresh, but the UI does not refresh until you click an element (or the new server) in the endpoint explorer pane on the left. This could probably be resolved by setting the selectedindex to the newly connected instance; however, I would rather see the endpoint explorer behave more like SSMS in that it will show me all the servers it's connected to with the ability to drill down into specific ones to view the queues.

**Comment by HEskandari** [comment] 2016-03-31 00:34
Thanks for reporting this. I'll mark this as a bug and we address the issue @fafachd reported and open another feature request for supporting multiple endpoints in the Endpoint Explorer.

Would that work?

**Comment by robbihun** [comment] 2016-03-31 13:47
@HEskandari Sounds great to me!

**Comment by fafachd** [comment] 2016-03-31 16:22
Perfect, thank you @HEskandari.

**Comment by HEskandari** [comment] 2016-10-20 07:49
Just verified in v1.5.7 and it is still reproducible and is not fixed.

**Comment by adamralph** [comment] 2016-10-20 08:44
https://github.com/Particular/ServiceInsight/issues/575 has been partially implemented which means we cannot verify whether this has been fixed in master. We will feature toggle the partial implementation off and then verify whether this has been fixed on master.

**Comment by adamralph** [comment] 2016-11-03 08:31
Since we are reopening closed bugs on the 1.5.8 milestone due to reverting master to 1.5.7 in #617, this issue has been moved from the 1.5.8 milestone to the Future milestone, to make a distinction.

This may be re-added to the 1.5.8 milestone if we decide to fix it before releasing 1.5.8.

**Comment by adamralph** [comment] 2016-11-15 08:48
This fix will be in the next release.

**Closed** 2016-11-15 08:47 UTC
Labels: Type: Bug

**Comment by adamralph** [comment] 2016-11-15 08:49
Thanks to @fafachd for raising this.
