### ISSUE TITLE
IoC not initialized

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceInsight#983] opened 2020-12-17 16:23 UTC
Fresh install of ServiceInsight 2.3.0 received this error. Attempted to full uninstall/reinstall and no luck.

Windows 10 Pro 19042.685

Anything else I can do to help troubleshoot?

```

System.InvalidOperationException: IoC is not initialized.
   at Caliburn.Micro.IoC.<>c.<.cctor>b__5_0(Type service, String key)
   at Caliburn.Micro.IoC.Get[T](String key)
   at Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   at ServiceInsight.Startup.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e) in /_/src/ServiceInsight/Startup/AppBootstrapper.cs:line 118
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at ServiceInsight.App.OnStartup(StartupEventArgs e) in /_/src/ServiceInsight/App.xaml.cs:line 52
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by HEskandari** [comment] 2020-12-18 00:10
@markgould We have already fixed this in the next coming version 2.4. 

This took a while to understand as the stack trace is absolutely not helpful (the underlying error is not reported), but the root cause was [this issue](https://github.com/Particular/ServiceInsight/issues/947). 

I'll keep the issue open until you can confirm it is fixed in 2.4.

**Comment by HEskandari** [comment] 2020-12-18 01:44
@markgould Version 2.4 is now released. Let us know if you get a chance to try it.

**Comment by markgould** [comment] 2020-12-18 03:01
That worked great, thanks!!

**Comment by HEskandari** [comment] 2020-12-18 03:14
@markgould awesome. I'll close this as duplicate.

**Comment by HEskandari** [comment] 2020-12-18 03:15
Duplicate of https://github.com/Particular/ServiceInsight/issues/947

**Closed by HEskandari** 2020-12-18 03:14 UTC
