### ISSUE TITLE
1.10.2 fixed an license check issue, but customers trying to import a "Advanced" license but a "The trial period is now over".

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#792] opened 2018-04-16 16:19 UTC
1.10.2 fixed an license check issue, but customers trying to import a "Advanced" license but a "The trial period is now over".

![image](https://user-images.githubusercontent.com/152998/38821945-4d0956f8-41a2-11e8-8250-b960f72286f4.png)

In this case I would expect a message similar to:

> The imported license type **"Advanced"** does not cover ServiceInsight. Please contact sales@particular.net to upgrade your license to type **"Enterprise"**. See https://particular.net/licensing for details.

**Comment by HEskandari** [comment] 2018-06-07 07:55
This is also covered in #803. I'll withdraw this as duplicate of #502.

**Closed by HEskandari** 2018-06-07 07:55 UTC
Labels: Licensing, UX
