### ISSUE TITLE
ServiceInsight asks for license every time I start it

### ISSUE THREAD

**Issue by dasjestyr** [Particular/ServiceInsight#722] opened 2017-04-07 17:26 UTC
Despite my providing a license, every time I start it up, it tells me that my trial period is over asks for a license. I'll give the license and it's fine until my next session.

**Comment by HEskandari** [comment] 2017-04-07 23:53
@dasjestyr Which version of SI are you running?

**Comment by dasjestyr** [comment] 2017-04-08 00:34
ServiceInsight 1.6.1
ServiceControl 1.34.0

**Comment by HEskandari** [comment] 2017-04-08 01:35
Sounds like an issue with the trial data in the registry. Would you be able to run SI as admin to ensure the license does actually get written to the registry?

I'll try to reproduce it on my end and will get back to you.

**Comment by dasjestyr** [comment] 2017-04-10 03:53
Sure. Let me know what to look for

**Comment by HEskandari** [comment] 2017-04-13 01:49
@dasjestyr I had a look. The only reasoning I have at this point is that you've had a license that is now expired (not trial). Is this the case? Could you please verify the stored license in your Registery and export and email it to me to verify?

The license can be stored in two locations (depending on how it is installed). It is either under HKLM or HKCU both in `SOFTWARE\ParticularSoftware\License`. If you have two licenses stored, please send both.

Please send an email to hadi.eskandari at particular dot net and don't share it publicly.

**Comment by dasjestyr** [comment] 2017-04-13 16:31
I've only had a trial license before purchasing this elastic license. I just made sure to run SI as admin, and it gave me the trial expired please give license prompt. I gave it the license again and it started. I then checked the registry. That registry key doesn't seem to be present in neither HKLM nor HKCU. I have:

HKCU\SOFTWARE\ParticularSoftware\PlatformInstaller
HKCU\SOFTWARE\ParticularSoftware\Profiler
HKLM\SOFTWARE\ParticularSoftware\PlatformInstaller
HKLM\SOFTWARE\ParticularSoftware\ServiceControl

And I don't see anything referring to the license

**Comment by HEskandari** [comment] 2017-04-14 04:55
@dasjestyr I have attached a screenshot of my registry. There should be a REG_MULTI_SZ type entry named "License" under "ParticularSoftware". 

![image](https://cloud.githubusercontent.com/assets/132117/25033556/5a4af0ca-2122-11e7-9398-a2c9e749e4bc.png)

Do you also have ServiceControl Management app on the same machine? If you do, you can use that to import the license.

**Comment by HEskandari** [comment] 2017-11-01 23:49
@dasjestyr did you have a chance to check your registry? is this still an issue? I wasn't able to reproduce it locally.

**Comment by dasjestyr** [comment] 2017-11-02 05:12
I did check it and it wasn't there. I ended up getting a new laptop in the meanwhile and installed it. At first it was working, then at some point it started doing it again. It's still an issue.

**Comment by HEskandari** [comment] 2017-11-02 05:50
@dasjestyr thanks for getting back to me. Would it be possible for you to export those two registry entries and email it to us (hadi dot eskandari at particular dot net)?

The registry entries are named `SOFTWARE\ParticularSoftware\License` and there are two copies of them, one under HKLM and another under HKCU. It only contains trial start date, license information (or trial license) so nothing confidential. 

I should be able to play the exact scenario with those keys and address the issue.

**Comment by dasjestyr** [comment] 2017-11-02 16:37
sent

**Comment by HEskandari** [comment] 2018-03-26 03:09
This is a duplicate of #776. The fix will be included in release [1.10.2](https://github.com/Particular/ServiceInsight/milestone/57?closed=1).

**Closed** 2018-03-26 03:09 UTC
Labels: Bug, Withdrawn
