### ISSUE TITLE
ServiceInsight (individual) uninstall completes silently without confirmation for the user

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#535] opened 2015-12-09 06:34 UTC
When the uninstallation of ServiceInsight completes (via individual uninstaller/setup), the installer exits abruptly and silently. This may give the false impression it crashed.

To improve this, there should be a screen at the end indicating the process is complete and the user should explicitly exit it.

**Comment by HEskandari** [comment] 2015-12-09 08:44
Isn't this more of an Platform Installer issue? Furthermore, I think that's a consistent behavior across all other products. I think @gbiellem could confirm (or say otherwise)

**Comment by sergioc** [comment] 2015-12-09 10:10
> Isn't this more of an Platform Installer issue?

I'm talking about the individual installer. I'll make that clear above.

**Comment by sergioc** [comment] 2015-12-09 10:11
> Furthermore, I think that's a consistent behavior across all other products.

That doesn't mean this behavior is correct. If it's consistent, then this issue should be duplicated for each of the other individual installers. Let's wait for @gbiellem to chime in.

**Comment by gbiellem** [comment] 2015-12-14 06:30
@sergioc @HEskandari  

Silently exiting the uninstall is the default  behavior for anything produced by Advanced Installer. 

If you feel strongly enough that this needs changing on all our installers it can be done -  See http://www.advancedinstaller.com/forums/viewtopic.php?f=5&t=28677#p74694

**Comment by sergioc** [comment] 2015-12-14 07:22
@gbiellem are you planning to change the SI installer and use what we now have for SC and SP?

**Comment by gbiellem** [comment] 2015-12-14 07:24
Yes... One at a time :)

**Comment by sergioc** [comment] 2015-12-14 07:28
Then we can close this issue when you're finished with that.

**Comment by gbiellem** [comment] 2015-12-14 08:36
:+1:

**Comment by distantcam** [comment] 2015-12-18 04:24
![image](https://cloud.githubusercontent.com/assets/1298847/11889255/30f2418c-a582-11e5-9c31-3dac0d112e4a.png)

I'm not sure what you guys are talking about. This is what happened when I ran the installer to uninstall SI.

**Comment by gbiellem** [comment] 2015-12-18 04:35
How did you kick off the uninstall?

**Comment by gbiellem** [comment] 2015-12-18 06:31
@distantcam  OK i see the confusion,  It only appears if the original installer is run to uninstall it.
That screen does not show if you run the uninstall via Add/Remove programs.

**Comment by distantcam** [comment] 2015-12-18 06:45
That is standard behaviour when you uninstall from the Program Manager, or at least standard behaviour from all the apps I've uninstalled that way.

**Comment by HEskandari** [comment] 2015-12-21 01:59
So can this be closed?

**Comment by gbiellem** [comment] 2015-12-21 02:33
@HEskandari It is standard behavior for installers produced by Advanced Installer to not display the final screen but it isn't standard behavior to not display the "Do you want to uninstall dialog" which the SI uninstall does not do.  So I'd say leave it open

I'm currently playing "whack-a-mole" with a PR to update Pulse's installer to behavior in a more standard manner and to ditch the black theme - See https://github.com/Particular/ServicePulse/pull/238/.   Once I get that one right I'll apply the same to SI which will address this.

**Comment by distantcam** [comment] 2016-03-11 02:02
@gbiellem So what's the deal with this? Can we get an update? I'm kinda itching to close this one.

**Comment by gbiellem** [comment] 2016-03-11 03:29
@distantcam since it isnt V6 or a critical bug ive not been working on it. 

If i'm permitted to do it then sure i could knock this over pretty quickly and we can close it

**Comment by distantcam** [comment] 2016-03-11 06:11
@gbiellem So it still requires fixing. That's all I wanted to know.

**Comment by HEskandari** [comment] 2016-10-20 07:39
@gbiellem Given v6 is over the line, can this be done now? I think @Particular/servicecontrol-maintainers are happy to give it a maintainer prio, but doesn't this belong to Platform Installer repo to begin with?

**Comment by gbiellem** [comment] 2016-10-20 09:38
@HEskandari nope this is nothing to do with platform installer.  Assign it to me and I'll raise a PR next week

**Comment by adamralph** [comment] 2016-10-20 09:40
Thanks @gbiellem - already assigned to you.

**Comment by HEskandari** [comment] 2016-10-20 09:41
@gbiellem I remembered we keep the setup files in this repo. Thanks.

**Comment by gbiellem** [comment] 2016-10-21 03:15
> @Particular/servicecontrol-maintainers are happy to give it a maintainer prio, 

@HEskandari  - are you merging maintainer groups already ;)

**Comment by HEskandari** [comment] 2016-10-21 03:20
@gbiellem Good catch...Fixed the 'typo'! :)

**Comment by gbiellem** [comment] 2016-10-21 03:50
@HEskandari all done I believe.  Can you check the resultant [installer]( https://builds.particular.net/viewLog.html?buildId=192989&tab=artifacts&buildTypeId=ServiceInsight_Build) and confirm you're happy with this.

**Comment by HEskandari** [comment] 2016-10-21 03:52
Thanks @gbiellem I'll verify.

**Comment by gbiellem** [comment] 2016-10-21 04:02
FYI when I run uninstall from Add/Remove programs I get this now which is what @sergioc wanted:

![capture](https://cloud.githubusercontent.com/assets/2351700/19586258/25d07afc-979f-11e6-9b8f-55419dedfba6.PNG)

This dialog isn't customizable through Advanced Installer though -  we can only enable or disable it so styling wise it will have to do

**Comment by sergioc** [comment] 2016-10-21 07:09
@gbiellem that's not what I wanted in this specific issue. What I wanted is the below screen to always show when uninstallation is finished:

![image](https://cloud.githubusercontent.com/assets/1298847/11889255/30f2418c-a582-11e5-9c31-3dac0d112e4a.png)

**Comment by adamralph** [comment] 2016-10-24 10:35
I'm a bit confused with this.

## 1.5.7

When I run the 1.5.7 installer I see our custom theme:

![image](https://cloud.githubusercontent.com/assets/677704/19642125/1b499220-99e4-11e6-9979-859548fce4ef.png)

After installation, when I run the 1.5.7 installer again and choose to remove the app, the uninstall finishes with:

![image](https://cloud.githubusercontent.com/assets/677704/19642169/5d90621c-99e4-11e6-9b09-c098af983812.png)

When I uninstall 1.5.7 from Windows Programs and Features I see:

![image](https://cloud.githubusercontent.com/assets/677704/19642218/a11fd6fc-99e4-11e6-8b29-a629d1cd0020.png)

And after clicking 'Yes' the custom themed installer window shows during un-installation and then closes without confirmation.

As I understand it, it is the closing without confirmation that is bad UX and the reason that this issue was raised.

## 1.5.8 (Not yet released)

When I run the 1.5.8 installer, I see a standard theme:

![image](https://cloud.githubusercontent.com/assets/677704/19642321/1041b29e-99e5-11e6-8dca-69849c5b6c62.png)

After installation, when I run the 1.5.8 installer again and choose to remove the app, the uninstall finishes with:

![image](https://cloud.githubusercontent.com/assets/677704/19642498/ec5ae6e2-99e5-11e6-9653-1a1f1b798476.png)

When I uninstall 1.5.8 from Windows Programs and Features I see:

![image](https://cloud.githubusercontent.com/assets/677704/19642400/5754128a-99e5-11e6-94a9-3995ca754256.png)

And after clicking 'Yes' the custom themed installer window shows during un-installation and then closes without confirmation.

---

Unless I'm mistaken, there is no functional difference between 1.5.7 and 1.5.8 in terms of uninstallation confirmation.

The only change we have made is to switch from our custom installer theme to the standard installer theme. This raises two questions:

1. Do we want to switch to the standard installer theme? Is this something we are doing across the platform? Besides loss of branding, as you can see from the dialog that is shown after uninstallation (when using the installer to uninstall), the information shown is poor in comparison. "Service Insight 1.5.7 has been successfully removed." vs "Completing the ServiceInsight 1.5.8 Setup Wizard". IMHO this is a UX regression. If the answer to this is no, then we need to revert the changes made in #605.

2. Can we change the installer to show the final dialog (in either case) when uninstalling using Windows Programs and Features?

**Comment by gbiellem** [comment] 2016-10-24 23:10
@adamralph 

> As I understand it, it is the closing without confirmation that is bad UX and the reason that this issue was raised.

That was the original reason, it was then dismissed and @sergioc asked for the theme to be updated as part of this issue and that is also the only reason it was left open  -See  https://github.com/Particular/ServiceInsight/issues/535#issuecomment-166181417)

In hindsight this was a bad call - we should have closed this issue and raised a new one rather than re-purposing this issue

> The only change we have made is to switch from our custom installer theme to the standard installer theme. Do we want to switch to the standard installer theme?

That theme was not a custom theme, It's an out of the box theme called "Aero" and if you scroll up to [here](https://github.com/Particular/ServiceInsight/issues/535#issuecomment-166181417) you 'll see we mentioned ditching it as it is broken out of the box.  See the associated SP bug for details.   All the other installer have been switched to the other theme for the same reason. So now they are all consistent.

> Unless I'm mistaken, there is no functional difference between 1.5.7 and 1.5.8 in terms of uninstallation confirmation.

Correct.  The change that introduced the "Are you sure you want to to uninstall" was not a code change, we got this by upgrading the Advanced Installer product from 8.x to 12,x on the build agents.  That functionality is built into all artifacts build with the new version.  This happened between the time this issue was backlogged and now which is why 1.5.7 already has this.  That build agent update was triggered by this issue,. Before that the uninstall from add/remove required no confirmation at all.

> Can we change the installer to show the final dialog (in either case) when uninstalling using Windows Programs and Features?

@distantcam  and I both mentioned above that this was default behavior and should not change,  There is a hack mentioned on the Advanced Installer forums that is for a much earlier version but I tried it and it did not work.  I don't believe it's worth the effort to try further,

> the information shown is poor in comparison. "Service Insight 1.5.7 has been successfully removed." vs "Completing the ServiceInsight 1.5.8 Setup Wizard". 

If you're unhappy with the wording update the installer.  These are just the defaults and can be changed

**Comment by distantcam** [comment] 2016-10-25 01:03
Ok, this issue ended up covering a range of things.

- **Installer theme change** - this was done to bring the SI installer in line with all the other product installers.
- **Are you sure confirmation** - this is a feature difference, and is also consistent with other products.
- **Uninstall complete dialog** - not done. After discussion it was decided this is non-standard. This is also the original issue but after discussion it was decided not to do this.

I'm going to close this issue now. If there are still issues with the installer please raise them in a new issue.

**Closed by distantcam** 2016-10-25 01:03 UTC
Labels: Type: Bug

**Comment by adamralph** [comment] 2016-10-25 09:30
@gbiellem thanks for the detailed explanation. It all makes sense now 😄

**Comment by adamralph** [comment] 2016-10-25 09:33
I raised #608 to represent the removal of the installer branding and put it on the 1.5.8 milestone. I also updated #605 to point at #608 rather than issue.

**Comment by sergioc** [comment] 2016-10-25 14:12
> **Uninstall complete dialog** - not done.

@distantcam but isn't that done as shown below?:

![image](https://cloud.githubusercontent.com/assets/677704/19642498/ec5ae6e2-99e5-11e6-9653-1a1f1b798476.png)

**Comment by adamralph** [comment] 2016-10-25 14:33
@sergioc that dialog is only shown when running the SI installer, in order to uninstall SI. When uninstalling SI via Windows Programs and Features, it is not shown. All the cases are described in https://github.com/Particular/ServiceInsight/issues/535#issuecomment-255705883

**Comment by sergioc** [comment] 2016-10-25 14:42
Then I don't understand why was this issue closed.

**Comment by adamralph** [comment] 2016-10-25 14:48
@sergioc see above

@gbiellem:

> @distantcam and I both mentioned above that this was default behavior and should not change, There is a hack mentioned on the Advanced Installer forums that is for a much earlier version but I tried it and it did not work. I don't believe it's worth the effort to try further,

@distantcam:

> Uninstall complete dialog - not done. After discussion it was decided this is non-standard. This is also the original issue but after discussion it was decided not to do this.

Based on that, the issue is withdrawn.

**Comment by sergioc** [comment] 2016-10-25 14:53
Whether it's default behavior or non-standard, not confirming the uninstallation was successfully completed is bad UX. Not all apps finish uninstalling silently, so I'm not sure where are the standards derived from.

The reason @gbiellem changed the uninstaller branding is because [we agreed to fix this issue when he'd get to do that](https://github.com/Particular/ServiceInsight/issues/535#issuecomment-164368288).

**Comment by adamralph** [comment] 2016-10-25 15:02
Removing the uninstaller branding to match the other products has been spun off into it's own issue and is part of the next release - https://github.com/Particular/ServiceInsight/issues/608 - that has value in it's own right, since we want SI to match the other products.

This means we can consider the case for confirmation after uninstall via Programs and Features separately. As I understand it, this affects all the Platform products: SC Management Utility, SI and SP. The assessment was that, as long as we are using Advanced Installer to build our installers, it is not worth us trying to introduce hacks to introduce the confirmation. If we feel strongly enough that this is required, then we need to consider switching to a different technology for building all three installers, other than Advanced Installer, and assess the ROI on that.

**Comment by sergioc** [comment] 2016-10-25 15:20
I feel strongly for adding that confirmation. This was the point of this issue. More important than branding. Also, I was under the impression that the lastest Wix installer engine version would allow to easily do that, that's why I agreed with @gbiellem to wait for the installer change to fix this.

**Comment by distantcam** [comment] 2016-10-26 02:11
> ...  I agreed with @gbiellem to wait for the installer change to fix this.

@sergioc Ahhh my mistake. I thought you agreed with @gbiellem that we should **not** include a confirmation at the end.

For consistency I think the issue of confirming the uninstall needs to be raised at a higher level (Platform Dev). All the product installers follow the same pattern so if one is changed all of them should be changed.

Another thing to consider is that the installation story for ServiceInsight will change once we introduce auto-updating.

**Comment by sergioc** [comment] 2016-10-26 07:06
OK @distantcam, I'll open an issue in PlatDev.
