### ISSUE TITLE
Dependencies refresh 

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#728] opened 2017-06-05 00:44 UTC
I note that several of the dependencies are significantly out of date. 

 * https://www.nuget.org/packages/Fody/1.29.3 2015-08-19
 * https://www.nuget.org/packages/PropertyChanged.Fody/1.50.3 2015-08-08
 * https://www.nuget.org/packages/Caliburn.Micro.Start/2.0.2 2015-03-16
 * https://www.nuget.org/packages/Newtonsoft.Json/6.0.8 2015-01-11

It seems the last refresh was done ~2 years ago. Is there some reason we are avoiding updating?

**Comment by HEskandari** [comment] 2017-06-05 05:23
@Particular/serviceinsight-maintainers Any objections on updating the dependencies?

**Comment by WilliamBZA** [comment] 2017-06-05 05:49
:+1: I have no objections. Probably something we should do more proactively too.

**Comment by adamralph** [comment] 2017-06-05 07:52
:shipit:

**Comment by adamralph** [comment] 2017-06-06 06:08
All my instincts (read OCD) tell me to update, but to play devil's advocate: why should we update?

**Comment by HEskandari** [comment] 2017-06-06 07:21
The reason you'd want to update regularly is general bug fixes and optimizations in the dependent frameworks. Arguably, SI is in a 'maintenance mode' until we decide on the direction, so there's little value in doing the updates.

**Comment by adamralph** [comment] 2017-06-06 07:44
> bug fixes and optimizations in the dependent frameworks

If those will result in observable changes in SI, should we have issues raised to represent those changes?

**Comment by HEskandari** [comment] 2017-06-06 07:46
That's what I think, hence the reason we've not upgraded: historically when the issues were raised, we'd upgrade to the latest version.

**Comment by adamralph** [comment] 2017-06-06 07:52
Should we look through the release notes history of the dependencies to see if there are any changes we will benefit from? Perhaps that exercise will also tell us that there would no observable changes in SI after we upgrade.

If there will be no observable changes, I'm not opposed to updating the dependencies as a purely internal change. In the future, I believe we should be keeping an eye on all releases of our dependencies and upgrading ASAP. Each time we do so we can raise issues to represent any observable changes that do result from the upgrade.

**Comment by WilliamBZA** [comment] 2017-06-06 08:45
According to our guidelines, we should only be [smoketesting nuget releases to ensure compatibility](https://github.com/Particular/PlatformDevelopment/tree/master/maintainers#what-does-a-maintainer-group-do). That doesn't seem applicable to a product like Service* though.

I think we should embrace updating as part of our process though. How often is our resolution to customer support cases "Are you running on the latest versions?" If we expect our customers to stay up to date, we should embrace the same spirit to do the same too. Especially with auto-update: it's a real slap in the face to force our users to stay up to date when we don't practice the same.

**Comment by adamralph** [comment] 2017-06-06 08:53
@WilliamBZA I tend to agree.

I propose that we update all the dependencies, but we read all the relevant release notes to determine what, if any, observable changes will result, and raise issues for each of them (all of which will be resolved by the PR which updates the dependencies).

**Comment by SimonCropp** [comment] 2017-06-06 09:56
so u r going to read 2 years worth of release notes for 30 packages?

**Comment by adamralph** [comment] 2017-06-07 11:53
I guess that's our penance for ignoring the releases for two years...

Currently there are 22 available updates, some which are only dev dependencies, e.g. GitVersion, analyzers, etc.

**Comment by SimonCropp** [comment] 2017-06-21 09:43
given u want to be running on the latest. why not update all of them and do a regression test. u dont need to read the release notes

**Comment by adamralph** [comment] 2017-06-21 11:01
I'm not sure how comprehensively we'll be able to regression test the UI.

**Comment by HEskandari** [comment] 2017-06-21 11:22
I think the biggest component we relying on is DevExpress which we're not going to update. The rest are mostly infrastructural (RestSharp, Fody, AutoFac and the likes) so by testing a few screens we can tell if things are fundamentally broken or not. Even if we test all the screens using a real-world/customer database it would take an hour at most as SI doesn't have that many screens.

**Closed** 2017-10-04 13:01 UTC
