### ISSUE TITLE
Message body display in Saga View

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#320] opened 2014-05-15 07:29 UTC
#### Problem

Current (SI v1.0) display of long message body properties is cut when too long (~20 characters; see highlighted below)

![image](https://cloud.githubusercontent.com/assets/3889023/2981240/46b08e16-dc02-11e3-9788-bb790e4affa8.png)

**Comment by johnsimons** [comment] 2015-05-29 00:59
Improvements for the saga diagram are being worked on as part of #452.
So closing this one

**Comment by adamralph** [comment] 2016-11-14 10:04
Re-opening, since #452 was closed.

**Comment by adamralph** [comment] 2016-11-14 10:05
Note: we should consider how, if at all, this relates to #320 and #624

**Comment by adamralph** [comment] 2016-11-14 10:05
Also consider the proposed solution in #452.

**Comment by HEskandari** [comment] 2017-03-15 01:29
The current implementation displays contents longer than 30 bytes as a link that you can use to see the whole content opened up in a dialog box.

Large message payloads displayed under each diagram node is by design. There's an open issue (#641) to try to address that.

**Closed by HEskandari** 2017-03-15 01:29 UTC
Labels: Type: Bug
