### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#39] opened 2013-10-13 13:30 UTC
As Dave, I would like to be notified when a new version of SI is available.
1. When ServiceInsight starts, check for the latest released version of Serviceinsight by calling: http://particular.net/api/products/ServiceInsight/Current
   - Note: since ServiceInsight is not yet released, it has no "current' entry and the above call will result in 404. 
   - For the prerelease versions of Serviceinsight use the following URI: http://particular.net/api/products/ServiceInsight/prerelease
2. Compare the version field number of the current release to the ServiceInsight version installed. 
3. If the current version is newer than the currently installed version, Display the following dialog:

```
A newer version of ServiceInsight [NewVersionNumber] is available for download at: http://particular.net/downloads. 
For more information on version [NewVersionNumber] see https://github.com/Particular/ServiceInsight/releases/tag/[NewVersionNumber] 
```
- Note: for an example of a release info, see: https://github.com/Particular/NServiceBus/releases/tag/4.0.5
- The user can start downloading ServiceInsight immediately by clicking "Download Now" (open the URL: http://particular.net/downloads#DownloadServiceInsight
- The dialog can be discarded using a click on "Cancel"

**Important Notes:**
- The URI calls to check the latest release  must not delay the loading time of ServiceInsight. (It must be done as a background async operation)
- If there is not internet connection or the Particular.net site is not accessible for any reason, do not display an error message
- Log the call to latest release and its result in the Logs pane of ServiceInsight (like you we do with calls to ServiceControl)
- The message dialog must be modeless (it must not interfere with the user's work; it is intended only to draw the user's attention; it can be implemented as a toast popup that can be hidden via a click as stated above).

**Comment by distantcam** [comment] 2016-01-06 10:05
Coming back to this one...

The platform installer does notify of updates, but isn't always run.

How do people feel about auto-updating like Google Chrome?

**Comment by johnsimons** [comment] 2016-01-06 22:43
This is a duplicate of https://github.com/Particular/PlatformDevelopment/issues/407, we should close one

**Closed** 2019-12-02 03:58 UTC
Labels: Feature
