### ISSUE TITLE
ServiceInsight 1.5.7 Fails on Startup

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#541] opened 2015-12-17 10:55 UTC
ServiceInsight fails on startup with this exception:

System.InvalidOperationException: IoC is not initialized.
   ved Caliburn.Micro.IoC.<.cctor>b__0(Type service, String key) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\IoC.cs:linje 13
   ved Caliburn.Micro.IoC.Get[T](String key) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\IoC.cs:linje 32
   ved Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\Bootstrapper.cs:linje 254
   ved System.Windows.Application.OnStartup(StartupEventArgs e)
   ved ServiceInsight.App.OnStartup(StartupEventArgs e) i C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\App.xaml.cs:linje 57
   ved System.Windows.Application.<.ctor>b__1_0(Object unused)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by HEskandari** [comment] 2015-12-17 11:39
Could you give us your configuration? Which .NET version / OS / etc.? there seem to be a deeper issue. Have you registered SI or running a (potentially expired) trial version? 

Have you tried [enabling the logging][1] and seeing if there's any other exception?

[1]:http://docs.particular.net/serviceinsight/how-logging-works

**Comment by cjoergensen** [comment] 2015-12-17 12:50
@HEskandari 

I'm running a Danish Win10 with .Net 4.6.01055. I've tried adding a 'log4net.config' file to the ServiceInsight directory, with this configuration:
```
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="LogFileAppender" type="log4net.Appender.FileAppender">
    <file value="Logs\Particular.ServiceInsight.txt"/>
    <appendToFile value="true"/>
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%date - [%-5level] - %logger - %message%newline"/>
    </layout>
  </appender>
  <root>
    <level value="ALL"/>
    <appender-ref ref="LogFileAppender" />
  </root>
</log4net>
```
However no logfiles are created on startup. I have tried uninstalling ServiceInsight and installing it again using the Platform installer, but it still fails on startup.

**Comment by cjoergensen** [comment] 2015-12-17 13:25
@HEskandari 

I found this in the c:\Users\[User]\AppData\Local\Particular\ServiceInsight\ folder:

```
2015-12-17 14:23:20.321 +01:00 [Debug] (ServiceInsight.Startup.CommandLineArgParser) Application invoked with following arguments: ["C:\Program Files (x86)\Particular Software\ServiceInsight\ServiceInsight.exe"]
2015-12-17 14:23:20.977 +01:00 [Information] (ServiceInsight.App) Starting the application...
2015-12-17 14:23:20.993 +01:00 [Error] (ServiceInsight.Framework.ExceptionHandler) An unhandled exception occurred. Error message is "IoC is not initialized.".
System.InvalidOperationException: IoC is not initialized.
   ved Caliburn.Micro.IoC.<.cctor>b__0(Type service, String key) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\IoC.cs:linje 13
   ved Caliburn.Micro.IoC.Get[T](String key) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\IoC.cs:linje 32
   ved Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings) i c:\Users\Rob\Documents\CodePlex\caliburnmicro\src\Caliburn.Micro.Silverlight\Bootstrapper.cs:linje 254
   ved System.Windows.Application.OnStartup(StartupEventArgs e)
   ved ServiceInsight.App.OnStartup(StartupEventArgs e) i C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\App.xaml.cs:linje 57
   ved System.Windows.Application.<.ctor>b__1_0(Object unused)
   ved System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ved System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by HEskandari** [comment] 2015-12-17 23:30
@cjoergensen I'm still trying to understand why this is happening. 

Do you see the splash screen when you run the app? or does it silently crash? Could you post a screenshot of what you see (if any)?

**Comment by cjoergensen** [comment] 2015-12-18 08:28
@HEskandari Here is what it looks like:
![oops](https://cloud.githubusercontent.com/assets/8087733/11892486/cb54e3f2-a568-11e5-82a2-647d4bb568a3.png)

If you mail me the build directly, it would properly get stuck in our antivirus filter. Could you upload the build to OneDrive/Dropbox and send me the details? My e-mail is: cgj(at)seas-nve(dot)dk

**Comment by HEskandari** [comment] 2015-12-21 01:58
Build 1.5.1 sent. Please let us know.

**Comment by cjoergensen** [comment] 2015-12-21 07:40
@HEskandari v1.5.1 has the same issue.

**Comment by HEskandari** [comment] 2015-12-23 02:07
@cjoergensen actually my bad, the PR with Caliburn upgrade is not merged in yet. I'll give you an update soon.

**Comment by cjoergensen** [comment] 2015-12-23 08:15
@HEskandari i keep on getting the 'IoC is not Initialized.' exception.

![screendump](https://cloud.githubusercontent.com/assets/8087733/11973078/71d1f77a-a955-11e5-8f40-331d1d918272.png)

**Comment by HEskandari** [comment] 2015-12-23 09:58
That's unfortunate...would it be possible for you to run ServiceInsight from source? I will try to setup a Danish Win10 and see if I can repro but so far I couldn't. Do you have another Danish Win 10 machine to verify if it consistently fails in that configuration?

**Comment by cjoergensen** [comment] 2015-12-29 08:30
@HEskandari When I run ServiceInsight from the source it works fine. 

When I get back at the office i will see if we are able to reproduce the error on machine with the same setup as mine.

**Comment by cjoergensen** [comment] 2016-01-11 12:36
@distantcam We have not been able to reproduce this error on other machines, with a similar setup as mine.

**Comment by HEskandari** [comment] 2016-01-11 22:47
Thanks for reporting that back. We thought it may have been an issue with JIT. @distantcam was working on a workaround.

**Comment by cjoergensen** [comment] 2016-01-19 09:10
Hi @HEskandari Just want to let you know that v. 1.5.3 works brilliant.

**Comment by HEskandari** [comment] 2016-01-19 09:13
@cjoergensen happy it works!

**Comment by distantcam** [comment] 2016-07-14 07:30
It's back! New error reported from 1.5.7+16.Branch.master.Sha.c29b94393a315079d401093011a66500c5b47923

```
Message: [InvalidOperationException: IoC is not initialized.]
 Caliburn.Micro.IoC.<.cctor>b__0(Type service, String key):10
 Caliburn.Micro.IoC.Get[T](String key):0
 Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings):0
 ServiceInsight.Startup.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e) in C:\Build\src\ServiceInsight\Startup\AppBootstrapper.cs:109
 System.Windows.Application.OnStartup(StartupEventArgs e):31
 ServiceInsight.App.OnStartup(StartupEventArgs e) in C:\Build\src\ServiceInsight\App.xaml.cs:57
 System.Windows.Application.<.ctor>b__1_0(Object unused):15
 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs):119
 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler):2
```

**Comment by HEskandari** [comment] 2016-11-15 06:56
@cjoergensen just wondering if you've had this error again, after upgrading to 1.5.3?

**Comment by cjoergensen** [comment] 2016-11-15 06:58
@HEskandari No. It gone...

**Comment by adamralph** [comment] 2016-11-15 09:31
Since the bug has re-surfaced in 1.5.7, I've changed the title accordingly. Given that we've only confirmed that it doesn't exist in 1.5.3, I guess it may also be present in any version back to 1.5.4.

**Comment by distantcam** [comment] 2016-11-30 09:47
I can reproduce this! It's caused by a binding redirect error between Autofac 3.5.2 and Autofac.Configuration 3.3.0. Removing the app.config file reproduces the same error.

**Comment by HEskandari** [comment] 2017-03-20 03:08
@distantcam Do we know how to fix this? If there's no way to fix it, I suggest documenting it and closing the issue (e.g. missing app.config)

**Comment by distantcam** [comment] 2017-03-20 03:57
@HEskandari There's no way to fix this through cod. It's a bad build/installation problem AFAIK. Document and close.

**Comment by HEskandari** [comment] 2017-03-29 02:59
@Particular/serviceinsight-maintainers After chatting with docs maintainers, the consensus is that there are too many things that can be broken when fiddling with config files (if that is the real reason this is happening for) and we don't need to document those.

As an alternative it was suggested that we can:

- Do binding redirects in code which would make the config file redundant.
- Catch the thrown exception and throw a more meaningful one.
- Check for config file existence upon startup.

**Comment by adamralph** [comment] 2017-03-29 18:20
> - Do binding redirects in code which would make the config file redundant.

That's my favourite!

**Comment by adamralph** [comment] 2018-01-30 08:25
We are closing this and advise a re-install of ServiceInsight if such problems occur. @cjoergensen if you are still experiencing problems, please let us know.

**Closed by adamralph** 2018-01-30 08:25 UTC
Labels: Bug

**Comment by ramonsmits** [comment] 2020-12-22 10:25
A user reported that version 2.4.0 resolved the `System.InvalidOperationException: IoC is not initialized.` exception for versions 2.0.0-2.3.0

**Comment by HEskandari** [comment] 2020-12-22 12:07
To be clear, there's a lot of scenarios where this could be reported as the error. Basically, anything going wrong during initialization phase (e.g. startup) of Caliburn.Micro would be reported with this error.
