### ISSUE TITLE
Message not being found when using search feature

### ISSUE THREAD

**Issue by msherin170** [Particular/ServiceInsight#813] opened 2018-11-02 16:10 UTC
I have 3 messages that come out at about the same timeframe every hour.  Each message body contains common content that i would like to use for searching.  I can see all 3 messages when looking at messages without a search filter.  When i enter in a search term of "VER"  it finds only 2 of the 3 messages.  All 3 messages contain the string of "VER" so the search should be able to find all 3.  The message that does not show is about 4 times larger than the other 2.  The 2 found messages are about 35,000 chars long and the larger message is about 139,500 chars long.  Is there some sort of limit size on searching? Could this be a potential bug?  I am supplying a file of the 3 messages.  The larger message is the 3rd message in the file.  If you need any further info, please let me know.  Thanks
[NServiceBus_messageexamples.txt](https://github.com/Particular/ServiceInsight/files/2543240/NServiceBus_messageexamples.txt)

**Comment by HEskandari** [comment] 2018-11-03 01:07
This is by design. ServiceControl will not store messages with large body content. The default value, as indicated on [this documentation](https://docs.particular.net/servicecontrol/creating-config-file#performance-tuning-servicecontrolmaxbodysizetostore), is 100Kb. 

If you're on ServiceControl 1.6 and above, you can tweak that configuration but keep in mind the throughput of your system and do proper capacity planning to ensure the ServiceControl instance functions properly. There is a guide for that which you can find [here](https://docs.particular.net/servicecontrol/servicecontrol-instances/hardware).

**Comment by msherin170** [comment] 2018-11-05 13:21
We have already adjusted the MaxBodySizeToStore key in  ServiceControl.exe.config, here is the value: <add key="ServiceControl/MaxBodySizeToStore" value="4096000" />  We are capturing and are able to view the larger message.  The problem comes in when we use ServiceInsight UI to filter the results based on content in the body of the message, This larger message is left out of the results, when we know for a fact the entered search/filter term is in the body of the message.

**Comment by HEskandari** [comment] 2018-11-06 04:46
I had out ServiceControl team had a look at it. I stand corrected, the config key `` does only control the storage of the messages (so you can see the in ServiceInsight). Only messages less than 85KB will be indexed. The [85kb limitation](https://github.com/Particular/ServiceControl/blob/develop/src/ServiceControl/Operations/BodyStorage/BodyStorageFeature.cs#L116) is enforced to avoid getting those objects in the Large Object Heap which would affect garbage collection and performance of ServiceControl.

**Comment by HEskandari** [comment] 2018-11-20 22:48
@msherin170 I'm closing this issue and mark it as `Withdrawn` as this is an expected behavior as far as ServiceInsight is concerned. Feel free to open an issue in [ServiceControl repository](https://github.com/Particular/ServiceControl) if you need to, as that is the right place.

**Closed by HEskandari** 2018-11-20 22:48 UTC

**Comment by udidahan** [comment] 2018-11-26 07:14
@msherin170 I take it that this VER attribute something you would frequently want to search by - is that right? Are there a limited number of attributes like it, or would it be very important for you to be able to search by anything and everything?
