### ISSUE TITLE
Sequence Diagram misplaces Handlers

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#570] opened 2016-03-16 12:30 UTC
## Symptoms

The Sequence Diagram misplaces the handler boxes in occasions and that results the message to appear out of order.

![screen1](https://cloud.githubusercontent.com/assets/8087733/13812222/2e7c7faa-eb7b-11e5-89ae-070987e5703e.png)
## Who's affected

This update is recommended for all users of ServiceInsight who rely on Sequence Diagram as it draws a more accurate sequence of messages in certain situations.

**Comment by HEskandari** [comment] 2016-06-24 00:38
@cjoergensen Would you be able to test this on the latest release of 1.5.6? I think this was fixed in 2a06575a5b4a453b90424d2768e7039d0b9fa840 and is a duplicate of #560.

**Comment by cjoergensen** [comment] 2016-06-24 07:38
Here is the sequence diagram from 1.5.6:

![screeen](https://cloud.githubusercontent.com/assets/8087733/16331270/633a8e9a-39ef-11e6-8987-fd0d2e0ecc83.png)

**Comment by HEskandari** [comment] 2016-06-24 10:08
@cjoergensen Would you be able to send us the ServiceControl database? If you want I can share a folder on Google drive for you to upload it.

**Comment by cjoergensen** [comment] 2016-06-24 11:29
sure thing. My email is: cgj(at)seas-nve.dk

**Comment by HEskandari** [comment] 2016-06-28 03:48
@cjoergensen Email set. Please let me know when you have uploaded it. Thanks.

**Comment by HEskandari** [comment] 2016-07-01 01:26
@cjoergensen I tried to restore it but it seems to be just too big for Raven Studio to handle. Would you be able to upload the DB folder content as [per this page](http://docs.particular.net/servicecontrol/backup-sc-database) into the Google drive please? That way with a simple file copy, I can restore your state and wouldn't have to go through the import process. Thanks.

**Comment by HEskandari** [comment] 2016-07-11 01:07
ping @cjoergensen

**Comment by cjoergensen** [comment] 2016-07-11 10:30
Im on vacation, but i will send you the data when im back.

**Comment by cjoergensen** [comment] 2016-08-01 11:04
@HEskandari I have uploaded the audit data. Have a look at messageid = 'a3f893de-25e0-4838-8d13-a655009bc7df'

**Comment by HEskandari** [comment] 2016-08-01 23:30
I'll have a look over the weekend as I'll be at the NDC conf for the rest of the week.

**Comment by HEskandari** [comment] 2016-08-15 06:36
@cjoergensen I finally got it up and running.  I can see the diagram with that message id. I can see that the *Started* message was at 2016-08-01T07:27:05.912881Z and the *Completed* message was processed at 2016-08-01T07:27:10.936081Z.

![image](https://cloud.githubusercontent.com/assets/132117/17656988/2bd555a6-6303-11e6-8fa9-0a560d288336.png)

With the fix you'll still see the two boxes for the Handlers but the order would be fixed.

**Comment by HEskandari** [comment] 2016-08-15 06:55
@cjoergensen this is the diagram generated with the fix. Does this look right now?

![image](https://cloud.githubusercontent.com/assets/132117/17657730/13123eca-6309-11e6-89fc-cd6845a079dc.png)

**Comment by cjoergensen** [comment] 2016-08-15 13:25
@HEskandari Looks great!

**Comment by HEskandari** [comment] 2016-08-18 09:21
@cjoergensen I have pushed this out to our staging, do you think you can have a look at [this pre-release](https://github.com/Particular/ServiceInsight/releases/tag/untagged-d9c13d60d4664ef4228a) and see if it works as expected?

**Comment by cjoergensen** [comment] 2016-08-19 07:34
Sure thing, but the link is broken...

**Comment by HEskandari** [comment] 2016-08-19 13:02
@cjoergensen The link works for me, might be a permission thing, see if this direct [download link](https://github.com/Particular/ServiceInsight/releases/download/untagged-d9c13d60d4664ef4228a/ServiceInsight-1.5.8.exe) works?

**Comment by HEskandari** [comment] 2016-08-23 23:56
@cjoergensen any updates? I'm waiting for your final confirmation to release the version, thanks beforehand :)

**Comment by cjoergensen** [comment] 2016-08-24 06:27
@HEskandari i keep getting 404 Error page when i click the links.

**Comment by HEskandari** [comment] 2016-08-24 08:10
@cjoergensen Apologies. Must be a permission thing. I'll upload it to the google drive and send you the link.

**Comment by HEskandari** [comment] 2016-09-06 00:55
@cjoergensen I have reviewed the updated database. I can see a couple of weird sorting issues in it. I have reopened the issue.

**Comment by HEskandari** [comment] 2016-10-18 03:45
@cjoergensen I'm back on this issue. The more I look at it, the more it feels like a time being out of sync between the endpoints. Did you at any point checked if the time between your endpoints are synced, preferably through an [NTP service](https://en.wikipedia.org/wiki/Time_server) to make sure they will remain in sync?

**Comment by HEskandari** [comment] 2016-10-20 07:58
Just to summarize where we're at with this issue - as it has been open for some time - here's the current status:

-The initial discrepancy reported was a bug in ordering of messages in the sequence diagram. That bug was reproduced with the database @cjoergensen provided and was patched. Changes are already merged with the master branch and will be included in the next release.
-When testing with a pre-release on a different database (updated?), we saw another issue. 
-We're trying to see if the second issue is potentially a time sync issue, since on the other customer databases I have tested, I haven't seen that behavior.

**Comment by adamralph** [comment] 2016-11-03 08:30
Since we are reopening closed bugs on the 1.5.8 milestone due to reverting master to 1.5.7 in #617, this issue has been moved from the 1.5.8 milestone to the Future milestone, to make a distinction.

This may be re-added to the 1.5.8 milestone if we decide to fix it before releasing 1.5.8.

**Comment by HEskandari** [comment] 2017-02-21 07:58
Hi @cjoergensen were you able to have another look at this? Should we proceed with releasing the interim bug fix, since the existing PR addresses the original issue you raised?

**Closed** 2017-03-13 18:44 UTC
Labels: Type: Bug, View: Sequence Diagram
