### ISSUE TITLE
SagaWindowViewModel.FetchOrderedSagaData - NullReferenceException

### ISSUE THREAD

**Issue by danielHalan** [Particular/ServiceInsight#738] opened 2017-07-12 16:25 UTC
Hi, 

Following Error occurs on ServiceInsight startup, causing it to Terminate.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceInsight.Saga.SagaWindowViewModel.<>c__DisplayClass31_0.<FetchOrderedSagaData>b__3(SagaUpdate update) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Saga\SagaWindowViewModel.cs:line 222
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at ServiceInsight.Saga.SagaWindowViewModel.FetchOrderedSagaData(Guid sagaId) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Saga\SagaWindowViewModel.cs:line 221
   at ServiceInsight.Saga.SagaWindowViewModel.RefreshSaga(SagaInfo originatingSaga) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Saga\SagaWindowViewModel.cs:line 170
   at ServiceInsight.Saga.SagaWindowViewModel.RefreshSaga(StoredMessage message) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Saga\SagaWindowViewModel.cs:line 152
   at ServiceInsight.Saga.SagaWindowViewModel.Handle(SelectedMessageChanged event) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Saga\SagaWindowViewModel.cs:line 103`

**Comment by HEskandari** [comment] 2017-07-13 00:52
Thanks for reporting it @danielHalan. I'm just wondering which version of SI were you using? There seems to be an issue with the Saga data that is potentially expired? Do you have this symptom on other instances of ServiceControl? 

Would you be able to securely share the database with us so we can reproduce it? If yes, I can email you the details on how.

**Comment by danielHalan** [comment] 2017-07-13 09:59
SI v1.7.1, you can contact me for diagnostics details, using my github handle _at_ gmail

**Comment by HEskandari** [comment] 2017-07-20 02:37
@danielHalan I had a look through the code and we are checking the data for being null.  Since you couldn't reproduce the issue either, should we close this for now? (we can always reopen it if you encounter it again).

**Comment by HEskandari** [comment] 2017-08-01 02:31
Keeping this issue open for now as I have received another report of this exact problem.

**Closed** 2017-08-18 09:12 UTC
Labels: Bug

**Comment by adamralph** [comment] 2017-08-22 10:39
@danielHalan thanks for raising this issue. This has been fixed in 1.7.2, which was released today: https://twitter.com/ParticularNews/status/899943683973361664
