### ISSUE TITLE
Messages Window selection is not highlighted

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#539] opened 2015-12-14 06:56 UTC
In some scenarios where there's one row in the Messages Window grid, the row doesn't get highlighted properly. Steps to repro:
1. Load SI and open a Sequence Diagram
2. Right click a message that's not the currently selected message in the Messages Window and select "Search by Message Id".
3. Observe that the Sequence Diagram displays the diagram correctly and the "Message Properties" window is also synchronized with the right message.
4. The Messages window has no row highlighted (there's only one).

This was also reported in #536 and asked in #513 as well.

**Comment by sergioc** [comment] 2015-12-14 07:45
@HEskandari what I noticed in https://github.com/Particular/ServiceInsight/issues/536 is if you right-click > search by msg id on a message that wasn't selected, then clear the search, it'll revert the selection to the previous message. This could explain why the row is not highlighted. See below:

![2015-12-14 at 08 44](https://cloud.githubusercontent.com/assets/493451/11775428/0a148aa2-a23f-11e5-8023-b06ff817f18e.gif)

**Comment by sergioc** [comment] 2020-08-31 08:42
Duplicate of #637

**Closed by sergioc** 2020-08-31 08:42 UTC
Labels: Bug, Message List View
