### ISSUE TITLE
Icons (shortcuts) not being placed in Start menu

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceInsight#557] opened 2016-01-18 19:18 UTC
A customer reported icons (shortcuts) not being installed in the start menu after using the GitHub releases installer 1.5.2. Apparently after running full platform installer initially ServiceInsight wasn't installed. After running SI 1.5.2 installer from GitHub, SI was installed but shortcuts weren't added to Start Menu.

Try to reproduce the issue and fix it.

**Comment by dvdstelt** [comment] 2016-01-18 19:47
Reproducing it wasn't an issue. But it's just the ServiceInsight icon that's not installing.

**Comment by HEskandari** [comment] 2016-01-18 23:01
Duplicate of #553 which is already fixed but not released. I'll publish a release for it shortly.

**Closed by HEskandari** 2016-01-18 23:01 UTC
Labels: Impact: S, Size: S, Tag: Up For Grabs
