### ISSUE TITLE
Splash screen high DPI and duration.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#583] opened 2016-05-18 10:51 UTC
It also is pretty annoying that the splash screen is displayed for quite some time. Its 8-10 seconds and then the applications pops up.

**Comment by distantcam** [comment] 2016-05-30 09:30
The duration is based on the startup of the app, which from a cold boot can take some time. In any case that's outside our control.

The DPI is a bug.

**Comment by distantcam** [comment] 2016-06-27 05:48
I'm going to close this as a duplicate of #504.

**Closed by distantcam** 2016-06-27 05:48 UTC
Labels: Size: S, Type: Bug
