### ISSUE TITLE
Display "Not Available" as value for TimeSent instead of displaying DateTime::MinDate or blank

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#429] opened 2015-02-03 06:35 UTC
At the moment, if a message does not contain the `TimeSent` header, ServiceInsight displays:
- blank in the message flow diagram
- displays `1/1/0001 12:00:00 AM` in the message grid 
- displays `1/1/0001 12:00:00 AM` in the saga view diagram
(not sure what it displays for the sequence diagram) 

It would be nice to display `TimeSent not available` in the message flow and the saga diagram views and simply `Not Available` for the TimeSent column in the message grid. 
Also if the `TimeSent` is being used it in date time computations it should display appropriate message there as well.

**Comment by weralabaj** [comment] 2015-07-16 11:41
@distantcam Turns out that fixing this issue requires changes in SI, SC and Saga Plugin.
I'm not sure why SC didn't handle TimeSent header missing properly (see [here](https://github.com/Particular/ServiceControl.Plugin.Nsb5.SagaAudit/blob/master/src/ServiceControl.Plugin.Nsb5.SagaAudit.Tests/When_a_message_with_no_headers_arrive.cs)) and how I can verify that now it's safe to modify the plugin.
Given that I think we should handle it as [FeatureDev issue 194](https://github.com/Particular/FeatureDevelopment/issues/194), not a bug and extend to other missing header values.

**Comment by distantcam** [comment] 2015-07-16 12:13
@weralabaj I agree that's the "proper" fix, but I thought this would still be worth fixing in SI too.

**Comment by weralabaj** [comment] 2015-07-16 12:23
@distantcam Without modifying SC and plugin we can only address display on flow diagram. We need to modify SC for fixing display in messages table, and both SC and plugin for sagas. 
Those are not big changes code-wise, but since they span across multiple repos I'd feel more confident with giving it more visibility by following the process. If you think that's not necessary I'm happy to do it here, but will need a good review ;)

**Comment by distantcam** [comment] 2015-07-16 12:33
@weralabaj The larger fix is being tracked in Particluar/FeatureDevelopment#194, but since it hasn't been dealt with I felt that waiting for the proper fix could be a long wait.

**Comment by distantcam** [comment] 2015-07-16 12:37
To be clear, I'm happy to call this a display issue within SI and fix it there, just to get the damn thing fixed.

**Comment by johnsimons** [comment] 2015-07-19 23:37
I am just afraid that if we do not actually fix the core issue in SC we kind of ignoring it and it will never get done. I do think this is a good opportunity to address both issues.
@weralabaj I'm happy to be part of the taskforce for it

**Comment by distantcam** [comment] 2015-07-20 02:14
@johnsimons Could you then run with the fix in SC please?

**Comment by johnsimons** [comment] 2015-07-20 02:16
@distantcam I think from what I gather it seems @weralabaj is interested in doing it.
I'm still working on the SC retries and after that one hopefully I get to upgrade SC to v5 core.

**Comment by weralabaj** [comment] 2015-07-20 08:12
I'll make sure it's not lost, need to catch up with @gbiellem, as Indu is away. The main question I have is how do we release this change if it's in multiple repos (SI, SP, SC, saga plugin)? Tips?

**Comment by distantcam** [comment] 2015-07-20 08:20
@weralabaj Given the data is transient anyway (after 30 days it's dumped from SC) I think the way forward is just fixing the code and ignoring previous bad values.

As for where to start, start at the source, the plugins and SC, then build out from there.

**Comment by gbiellem** [comment] 2015-07-20 08:24
@distantcam  - I don't think sagaaudit is part of the 30 day cleanup in current SC.  I believe that @SimonCropp and @SzymonPobiega added it as part of  the SagaAudit fix which has not been released

**Comment by distantcam** [comment] 2015-07-20 09:39
@gbiellem pretty sure it is as every 30 days I need to reinsert saga data for testing SI.

**Comment by gbiellem** [comment] 2015-07-20 11:15
@distantcam Nope - I checked. In 1.5.3 the cleanup only removes items from ProcessedMessages.

The deletion uses this this index  See https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/RavenDB/Expiration/ExpiryProcessedMessageIndex.cs

So documents in the SagaHistories collection aren't cleaned up. 

In develop the Index was changed to include the restructured saga audits - See https://github.com/Particular/ServiceControl/blob/develop/src/Particular.Backend.Debugging.RavenDB/Expiration/ExpiryProcessedMessageIndex.cs

**Comment by distantcam** [comment] 2015-07-21 01:47
@gbiellem So is it just the messages that disappear after 30 days? If there's no message information what's the point of keeping the saga data?

**Comment by gbiellem** [comment] 2015-07-21 02:26
@distantcam 

In 1.5.3 the SagaAudit creates a document per saga and then updates it with subsequent SagaAudit messages so there there isn't a nice way to age them out - When do you consider it stale?

@SimonCropp 's fix in develop changed this approach to a document per msg approach similar to the processed messages primarily to address concurrency issues when writing the saga data, the side effect was it was easy for him to extend the expiry to include saga audit data.

**Comment by gbiellem** [comment] 2015-07-21 02:35
@distantcam - agree regarding no migration.  That's what @weralabaj and I discussed yesterday

**Comment by johnsimons** [comment] 2015-08-11 04:28
Fixed in #484

**Closed by johnsimons** 2015-08-11 04:28 UTC
Labels: Bug, ready
