### ISSUE TITLE
Saga View Long property window does not display displayed property name

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#355] opened 2014-07-10 06:34 UTC
### Repro
- Click on long property in Saga view

![image](https://cloud.githubusercontent.com/assets/3889023/3535193/f023a594-07fb-11e4-9245-7643a00c7f45.png)
- The log property popup window does not contain any information about the property name 
  - (it also covers the original property display and it is not drag-able so you need to close the popup in order to recall to which property it applies)

![image](https://cloud.githubusercontent.com/assets/3889023/3535199/2825e6e6-07fc-11e4-9c43-5821ffe3e43e.png)

**Comment by johnsimons** [comment] 2015-05-14 08:17
@dannycohen where do u want the property name to be displayed ? the window title ?

**Comment by dannycohen** [comment] 2015-05-14 11:40
@johnsimons - I think windows Title is good enough. 
// CC @sergioc

**Comment by sergioc** [comment] 2015-05-14 13:06
In addition to the message name, so: "VideoStore.Messages.Commands.SubmitOrder - **Property name**"

**Comment by johnsimons** [comment] 2015-05-14 23:41
> In addition to the message type, so: "VideoStore.Messages.Commands.SubmitOrder - Property name"

@sergioc that does not work, the problem is that "VideoStore.Messages.Commands.SubmitOrder - Property name" could be too long and it gets trimmed, so I think we should just go with the **PropertyName**

**Comment by sergioc** [comment] 2015-05-15 08:11
@johnsimons Without mentioning the message it belongs to, if you leave that window open, you'll loose track of which message the property belongs to. How about:

![screenshot 2015-05-15 10 10 43](https://cloud.githubusercontent.com/assets/493451/7649176/beb44fbc-faea-11e4-9b5a-c16ece1b1067.png)

**Comment by distantcam** [comment] 2017-03-14 07:34
Closing this in favour of #641

**Closed by distantcam** 2017-03-14 07:34 UTC
Labels: Type: Bug
