### ISSUE TITLE
Strings are not represented correctly in SagaView

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#668] opened 2016-12-06 08:19 UTC
There are various issues related to displaying values, since there's no type information and everything is a string.

- Empty strings are left empty on right hand side of the equal signs ("="). The lack of value should be clearly communicated.
- Trailing white space is not represented at all.
- You can't tell if empty space is an empty string or a series of spaces (or potentially tabs?)
- _Leading_ whitespace, in a way, is shown, by the offset of the RHS value but hard to tell how many white spaces there are.

**Comment by adamralph** [comment] 2016-12-06 08:23
@HEskandari isn't this a duplicate of #642?

**Comment by HEskandari** [comment] 2016-12-06 08:35
@adamralph I thought we agreed to keep them separate since #642 is more straightforward than this.

**Comment by adamralph** [comment] 2016-12-06 08:38
@HEskandari oh, sorry! *empty* strings. All good.

**Comment by HEskandari** [comment] 2017-02-28 23:10
@adamralph did we discuss how this needs to be tackled? How do we represent strings on the UI? pinging @sergioc

**Comment by sergioc** [comment] 2017-03-01 08:41
@HEskandari can you share screenshot(s) that illustrate the issue?

**Comment by HEskandari** [comment] 2017-03-01 09:18
@sergio That's exactly the point :) If you have a string with leading or trailing space, the way it is currently displayed on the UI makes it unclear.

Imagine this text (where a dot is a space) "...text content..." the way we display it on the UI is:

`Property =    text content`

You *may* notice the extra margin on the left (after the equal) but there's no way to find out there's an space on the right hand side.

**Comment by adamralph** [comment] 2017-03-01 12:50
@HEskandari AFAIK we haven't come up with a solution yet. The best I can suggest is wrapping with double quotes (with a double quote character within a string escaped with a backslash).

**Comment by HEskandari** [comment] 2017-03-06 06:38
@sergioc I have generated a saga data to reflect the problem:

![image](https://cloud.githubusercontent.com/assets/132117/23599182/8582a894-0293-11e7-9946-82dca052129e.png)

There are the following in the picture above:

- For `LeadingSpaceString` value, although the space can be seen, it is not clear how many characters there are.
- There's no indication of any space characters in `TrailingSpaceString` value.

**Comment by sergioc** [comment] 2017-03-06 09:47
> wrapping with double quotes (with a double quote character within a string escaped with a backslash).

@adamralph that sounds like something belonging to a terminal/command prompt or code, not a GUI.

Here's a couple of ideas:

### Use tight ellipsis (characters) to underline empty spaces:

The [ellipsis character](http://www.fileformat.info/info/unicode/char/2026/index.htm) is not regularly used, so placing there greyed out can convey they're used as an aid in recognizing empty spaces, not as an actual part of the string.

![empty-string-si-ellipsis-underscore](https://cloud.githubusercontent.com/assets/493451/23604712/1d49048c-025a-11e7-8a17-a3b7e07d0d5d.png)


### Use solid blocks:

Another representation that is unlikely to be confounded as an actual part of the string.

![empty-string-si-block-placeholder](https://cloud.githubusercontent.com/assets/493451/23604719/2282ab74-025a-11e7-80e5-64d7be0d9fad.png)

**Comment by sergioc** [comment] 2017-03-06 09:50
I've updated the screens above to visualize the options for empty suffixes as well.

**Comment by adamralph** [comment] 2017-03-06 20:51
> @adamralph that sounds like something belonging to a terminal/command prompt or code, not a GUI.

Or in a debugging app? This isn't an end user application. It's for developers.

**Comment by sergioc** [comment] 2017-03-07 07:08
It's and end user app for developers. I understand devs are familiar with how to read escaped characters, but I'm not so sure if they'd expect that as the value of a string represented in GUI list. If you feel strongly for that option, we can always test.

**Comment by adamralph** [comment] 2017-03-07 09:03
It seems like the simplest and most obvious solution. I think worth a test. Perhaps we could use some nicely stylised double quote characters?

**Comment by HEskandari** [comment] 2017-03-07 09:12
VisualStudio already has an option to display spaces in the IDE. Should we adopt the same thing here? Here's a screenshot.

![image](https://cloud.githubusercontent.com/assets/132117/23649377/5df3195a-0372-11e7-85db-7f2f3875b02d.png)

You can enable it via CTRL+R,CTRL+W.

**Comment by adamralph** [comment] 2017-03-07 09:15
@HEskandari that's not a bad idea! If the space indicators are sufficiently coloured to distinguish them from genuine `·` characters, then I think that could work.

**Comment by HEskandari** [comment] 2017-03-07 09:17
@adamralph agreed. The one in VS is clearly different. It is a bit larger and a bit elevated than the regular dot but we can make it more distinguishable with a different color maybe.

**Comment by adamralph** [comment] 2017-03-07 09:20
The character I pasted there was a [unicode middle dot](http://www.fileformat.info/info/unicode/char/b7/index.htm) rather than a full stop (period).

I.e. `·` vs `.`

I think it would need to be bold and colored differently.

A [unicode bullet] is another option: `•`

**Comment by sergioc** [comment] 2017-03-07 10:01
I'm happy with being consistent with VS.

**Comment by adamralph** [comment] 2017-03-07 10:09
I think the unicode bullet is probably too much. I propse the middle dot in grey. @sergioc what do you think? Could you do some mock ups?

**Comment by sergioc** [comment] 2017-03-07 10:56
Dots:

![empty-string-dots](https://cloud.githubusercontent.com/assets/493451/23653489/0dfb18f2-032d-11e7-9d92-4ebe01e7c529.png)

Bullets:

![empty-string-bullets](https://cloud.githubusercontent.com/assets/493451/23653496/148e2a60-032d-11e7-9112-87b32e795784.png)

**Comment by sergioc** [comment] 2017-03-07 10:57
Despite inconsistency with VS, I think the [block characters](https://cloud.githubusercontent.com/assets/493451/23604813/885c6610-025a-11e7-8401-d1979a42c7e6.png) work best.

**Comment by adamralph** [comment] 2017-03-07 11:09
My vote would be middle dots. It aligns with VS, VS Code, Sublime Text, TortoiseGitDiff, WinMerge, and I suspect countless others.

**Comment by sergioc** [comment] 2017-03-07 12:07
@adamralph I'm not entirely convinced. I think we should test this. Just like escaped characters, the context is different. Those dots show in editors. SI Saga properties don't show in an editor, they're static text. As such different mental models are at play.

**Comment by adamralph** [comment] 2017-03-07 17:28
@sergioc fair enough, I'm happy to test a few options.

**Comment by HEskandari** [comment] 2017-03-17 03:29
How do we proceed with this?

**Comment by sergioc** [comment] 2017-04-10 17:53
@HEskandari I finally found this issue again (thanks @adamralph). I'll see if I can test the options above this week.

**Comment by sergioc** [comment] 2017-09-20 16:54
I tested the different options back in the meanwhile and no one immediately identified any of the proposed characters as a space. However I did get the suggestion to use `˽` instead, which makes sense to me. Thoughts?

**Comment by HEskandari** [comment] 2017-09-25 01:16
That works for me. @Particular/serviceinsight-maintainers thoughts?

**Comment by HEskandari** [comment] 2018-05-23 02:40
@Particular/serviceinsight-maintainers ☝️ ping

**Comment by adamralph** [comment] 2018-05-24 11:37
Can we get a mock up of `˽`?

**Comment by sergioc** [comment] 2018-05-24 11:45
<img width="497" alt="image" src="https://user-images.githubusercontent.com/493451/40483565-b8331134-5f58-11e8-96be-395b952e0a2d.png">

**Comment by sergioc** [comment] 2018-05-24 11:46
<img width="494" alt="image" src="https://user-images.githubusercontent.com/493451/40483588-d25756f6-5f58-11e8-8982-c8d6e7f310fb.png">

**Comment by adamralph** [comment] 2018-05-24 14:09
I've attempted to scale it down to actual size:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/493451/40483588-d25756f6-5f58-11e8-8982-c8d6e7f310fb.png">

I think this OK. Given that we have the grey colour to distinguish from the actual content, the actual char used is not of huge importance.

**Comment by HEskandari** [comment] 2018-05-28 02:12
Since we have an agreement on the solution, I'll add this to the next milestone.

**Comment by Scooletz** [comment] 2018-06-04 17:53
Are there any PRs with the tests you did @sergioc @adamralph ? I see none linked to this issue. It'd be easier to "just merge it" and ship under the 1.10.3.

**Comment by HEskandari** [comment] 2018-06-05 00:44
I don't think there's been a PR raised for this issue. The UI you see are mock ups.

**Comment by Scooletz** [comment] 2018-06-05 09:39
Thank you. I'm new to XAML. We could either format `SagaUpdatedValue.NewValue` or do some formatting in the view itself. What would be a preferred way of doing it?

**Comment by HEskandari** [comment] 2018-06-06 10:32
@sergioc Screenshot from the app. Does this look alright @sergioc?

![image](https://user-images.githubusercontent.com/132117/41033109-c00f75d0-69c8-11e8-8426-925f40213fe1.png)

**Comment by sergioc** [comment] 2018-06-06 14:58
it seems like the first non-breaking space character on the left is not left-aligned with the values above and below. There should also be some more space between the a non-breaking space character and another value:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/493451/41046523-dc36e6bc-69aa-11e8-9c1f-d27708d59faf.png">

The rest looks good!

**Comment by HEskandari** [comment] 2018-06-07 01:14
@sergioc 

I have already added one space before and after the `˽` character. Maybe change it to two?
Left align is probably due to the added whitespace to the beginning. I think I can fix that.

**Comment by HEskandari** [comment] 2018-06-07 05:09
Even though I've fixed the spacing issue above, there are other side effects that I couldn't quite get rid of. This would require more time to sort those out and given the limited time, I am going to exclude this from the milestone. 

The issue can be seen here:

![image](https://user-images.githubusercontent.com/132117/41079330-c1df1356-6a64-11e8-9d0d-a0646c3af910.png)

**Comment by sergioc** [comment] 2018-06-07 07:42
> note how the date has the space moniker as well

should we add a tooltip to the non-breaking space character so to provide a fallback explanation?

> The issue can be seen here

Are you talking about character spacing, seen in `eT` from `FalseTrue`?

How about we switch to a mono-space font to get rid of spacing issues?

**Closed** 2020-09-03 23:45 UTC
Labels: Bug, Saga View
